function fig = pulsetool()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

% Versions listed as date, YY_MM_DD
% 01_01_17 Option to keep old magnetization, pulsephase in degrees, modified
%	to allow "pulsetoolfunc simulate" from command line.


globalstr = strcat('global filename;',...
'global b1 phase Nrf;',...
'global b1max Tp pulsephase;',...
'global T1 T2;',...
'global MOX MOY MOZ;',...
'global offsetmax offsetsteps offset;',...
'global offsets Mx My Mz; ',...
'global B1 b1tx b1ty b1null;',...
'global pauseval;');

bgcolor = [0.752941176470588 0.752941176470588 0.752941176470588];

h0 = figure('Color',bgcolor, ...
	'CreateFcn',globalstr, ...
	'Name','Pulsetool 2005 - BPhys8147', ...
	'PaperUnits','points', ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc loadfile', ...
	'ListboxTop',0, ...
	'Position',[120 195 80 17.25], ...
	'String','Load', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc gui_to_data;pulsetoolfunc simulate', ...
	'ListboxTop',0, ...
	'Position',[118.5 73.5 80 17.25], ...
	'String','Simulate', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc gui_to_data;pulsetoolfunc fft', ...
	'ListboxTop',0, ...
	'Position',[118.5 123 80 17.25], ...
	'String','FFT', ...
	'Tag','PushbuttonFFT');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Enable','off', ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[74.25 217.5 121.5 18.75], ...
	'Style','edit', ...
	'Tag','EditFilename');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[17.25 222 46.5 15], ...
	'String','filename:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[17.25 197.25 46.5 15], ...
	'String','b1max: (Hz)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[17.25 171.75 40.5 15], ...
	'String','Tp: (s)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[17.25 147.75 60 15], ...
	'String','phs: (deg)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[74.25 194.25 37.5 18.75], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditB1max');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[74.25 169.5 36.75 18.75], ...
	'String','0.005', ...
	'Style','edit', ...
	'Tag','EditTp');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[74.25 145.5 36.75 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditPulsephase');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[288.75 216.75 39 18.75], ...
	'String','1000', ...
	'Style','edit', ...
	'Tag','EditT1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[234.75 218.25 32.25 15], ...
	'String','T1: (s)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[288.75 194.25 39.75 18.75], ...
	'String','1000', ...
	'Style','edit', ...
	'Tag','EditT2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[234.75 195 31.5 15], ...
	'String','T2: (s)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[74.25 72 38.25 18.75], ...
	'String','2000', ...
	'Style','edit', ...
	'Tag','EditSimBW');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[20.25 76 54 15], ...
	'String','SimBW: (Hz)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[75 46.5 36 18.75], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditOffsetsteps');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[21 48.75 46.5 15], ...
	'String','offsetsteps:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[288.75 147 33 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditMOX');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[234.75 147.75 23.25 15], ...
	'String','MO:', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[332.25 147 31.5 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditMOY');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[372.75 147 32.25 18.75], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditMOZ');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc plotpulse', ...
	'ListboxTop',0, ...
	'Position',[120 171 80 17.25], ...
	'String','Display Shape', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[18 241.5 175.5 16.5], ...
	'String','Pulse Info', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[233.25 240 175.5 16.5], ...
	'String','Settings', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[19.5 94.5 175.5 16.5], ...
	'String','Offset Profile', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[230.25 93.75 175.5 16.5], ...
	'String','Rotations', ...
	'Style','text', ...
	'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[312 27.75 46.5 15], ...
	'String','pause: ', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[347.25 27.75 55.5 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditPause');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[288.75 170.25 36 18.75], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditOffset');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[234.75 171 46.5 15], ...
	'String','offset: (Hz)', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc play', ...
	'ListboxTop',0, ...
	'Position',[330.75 72.75 72.75 17.25], ...
	'String','Play', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[228.75 73.5 90.75 16.5], ...
	'String','Show B1eff', ...
	'Style','checkbox', ...
	'Tag','CheckboxB1eff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc calcflipangle', ...
	'ListboxTop',0, ...
	'Position',[119.25 146.25 80 17.25], ...
	'String','Calc Flip Angle', ...
	'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','pulsetoolfunc rotate', ...
	'ListboxTop',0, ...
	'Position',[331.5 49.5 72 18], ...
	'String','Rotate', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[228.75 57.75 90.75 16.5], ...
	'String','Show Trace', ...
	'Style','checkbox', ...
	'Tag','CheckboxTrace');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[228.75 42 78.75 17.25], ...
	'String','B1eff Frame', ...
	'Style','checkbox', ...
	'Tag','CheckboxFrame');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[228.75 25.5 78.75 17.25], ...
	'String','Shadow', ...
	'Style','checkbox', ...
	'Tag','CheckboxShadow', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[118.5 48.75 43.2 16.8], ...
	'String','Mx', ...
	'Style','checkbox', ...
	'Tag','CheckboxMx', ...
	'Value',0);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[118.5 30 43.2 16.8], ...
	'String','My', ...
	'Style','checkbox', ...
	'Tag','CheckboxMy', ...
	'Value',0);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[118.5 12 43.2 16.8], ...
	'String','Mz', ...
	'Style','checkbox', ...
	'Tag','CheckboxMz', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[175 48.75 43.2 16.8], ...
	'String','Mxy', ...
	'Style','checkbox', ...
	'Tag','CheckboxMxy', ...
    'Value', 1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[175 30 43.2 16.8], ...
	'String','Phs', ...
	'Style','checkbox', ...
	'Tag','CheckboxPhase');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[175 12 43.2 16.8], ...
	'String','Err', ...
	'Style','checkbox', ...
	'Tag','CheckboxErr');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[21 24.75 80.25 17.25], ...
	'String','Refocus', ...
	'Style','checkbox', ...
	'Tag','CheckboxRefocus');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'ListboxTop',0, ...
	'Position',[20.8 9 80.25 17.25], ...
	'String','Init M0', ...
	'Style','checkbox', ...
	'Tag','CheckboxInitM0', ...
	'Value',1);

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',bgcolor, ...
	'Callback','close all', ...
	'ListboxTop',0, ...
	'Position',[180 270 72 18], ...
	'String','Close', ...
	'Tag','butClose');

movegui('northeast')
if nargout > 0, fig = h0; end
